[NAE-1946] Remote file connector to S3
netgrif/petriflow pull request #14
Opened 2024-02-12 11:45 UTC by martinkranec

- remove remote maxLength

2024-02-12 19:47 UTC, mazarijuraj requested changes

2024-02-12 19:47 UTC, mazarijuraj commented on petriflow.schema.xsd
> +    <xs:restriction base="xs:string"/>
If there is no restriction please remove this simple type and change the element `remote`  in complex type `data` to type `xs:string`

2024-09-12 12:22 UTC, machacjozef approved these changes

2024-09-12 12:23 UTC, renczesstefan approved these changes

2024-09-12 12:25 UTC, merged